### PR TITLE
Optional title and message

### PR DESCRIPTION
**Pull request by Taylor123**

### CODE REVIEW

**Comment by tschoffelen** [comment]
Making them optional is fine, but this also removes the default values as far as I can tell.

Wouldn't passing `null` to the `title` and `message` params achieve your intended result?

**Comment by Taylor123** [comment]
@tschoffelen on iOS you'll get the error: `NSNull cannot be converted to NSString` and on the android implementation any falsy value will be replaced with the default string

**Comment by Taylor123** [comment]
i could add another argument to the function and adjust if you'd prefer it

**Comment by tschoffelen** [comment]
That might be a better solution indeed!

**Comment by tschoffelen** [comment]
Great! This also fixes #7. Thanks!

**Comment by tschoffelen** [comment]
Published to NPM as `react-native-email-link@1.3.0`.

**Pull request merged**
